# Generated by Django 6.0.5 on 2026-05-12 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('frecuencia', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='semanal', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('tiene_canasto', models.BooleanField(default=False, help_text='El cliente ya tiene el canasto físico')),
                ('tiene_tarro_organicos', models.BooleanField(default=False, help_text='El cliente ya tiene el tarro para desechos orgánicos')),
                ('proxima_entrega', models.DateField(blank=True, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('ultimo_pedido', models.ForeignKey(blank=True, help_text='Pedido anterior — base para repetir la selección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripcion_origen', to='tienda.pedido')),
            ],
            options={
                'verbose_name': 'Suscripción Despensa',
                'verbose_name_plural': 'Suscripciones Despensa',
                'ordering': ['-creada'],
            },
        ),
    ]
