# Generated by Django 6.0.5 on 2026-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_suscripcion_despensa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Unidades disponibles en inventario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5, help_text='Envía alerta al productor cuando baje de este número'),
        ),
        migrations.AddField(
            model_name='productor',
            name='email',
            field=models.EmailField(blank=True, help_text='Para notificaciones automáticas de stock agotado', max_length=254),
        ),
        migrations.AddField(
            model_name='productor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
