# Generated by Django 6.0.5 on 2026-05-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_stock_email_productor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_mayor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio al por mayor (restaurantes, revendedores)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_mayor',
            field=models.CharField(blank=True, help_text='Ej: caja x 12, bulto x 50kg', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio al detal (consumidor final)', max_digits=10),
        ),
    ]
