# Generated by Django 6.0.5 on 2026-05-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_precio_mayor_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caducidad',
            field=models.CharField(blank=True, help_text='Ej: 6 meses sellado, refrigerado 15 días', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='cobertura_envio',
            field=models.CharField(choices=[('local', 'Solo local'), ('nacional', 'Envío nacional')], default='local', help_text='¿Se puede enviar a todo el país?', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='ingredientes',
            field=models.TextField(blank=True, help_text='Lista de ingredientes o componentes'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiempo_espera',
            field=models.PositiveIntegerField(default=0, help_text='Días de espera promedio por pedido'),
        ),
    ]
