# Generated by Django 6.0.5 on 2026-05-17 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_pedido_usuario_direccionenvio_perfilcliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tiempo_prep', models.PositiveIntegerField(default=15, help_text='Minutos de preparación')),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Media'), ('dificil', 'Difícil')], default='facil', max_length=10)),
                ('foto', models.ImageField(blank=True, upload_to='recetas/')),
                ('video_url', models.URLField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='estado_editorial',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('destacado', 'Destacado')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del lote actual', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='meses_temporada',
            field=models.JSONField(blank=True, default=list, help_text='Meses de cosecha, ej: [3,4,5] = mar-may'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sugerencias_uso',
            field=models.TextField(blank=True, help_text='Tips de uso, maridajes, combinaciones sugeridas'),
        ),
        migrations.AddField(
            model_name='productor',
            name='estado_editorial',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('publicado', 'Publicado'), ('destacado', 'Destacado')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='productor',
            name='tipo_acuerdo',
            field=models.CharField(choices=[('acopio', 'Centro de acopio'), ('directo', 'Envío directo'), ('ambos', 'Ambos')], default='acopio', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='caducidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='certificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cobertura_envio',
            field=models.CharField(choices=[('local', 'Solo local'), ('nacional', 'Envío nacional')], default='local', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='historia',
            field=models.TextField(blank=True, help_text='La historia detrás de este producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ingredientes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio al detal', max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_mayor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio al por mayor', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tiempo_espera',
            field=models.PositiveIntegerField(default=0, help_text='Días de espera promedio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(default='unidad', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_mayor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='productor',
            name='email',
            field=models.EmailField(blank=True, help_text='Para notificaciones automáticas de stock', max_length=254),
        ),
        migrations.AlterField(
            model_name='productor',
            name='historia',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productor',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='tiene_canasto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='tiene_tarro_organicos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='ultimo_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripcion_origen', to='tienda.pedido'),
        ),
        migrations.CreateModel(
            name='ClienteCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('nit', models.CharField(blank=True, max_length=20)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente Corporativo',
                'verbose_name_plural': 'Clientes Corporativos',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_corporativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.clientecorporativo'),
        ),
        migrations.CreateModel(
            name='ConversacionAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones del Agente',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='MensajeAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('user', 'Cliente'), ('assistant', 'Agente')], max_length=10)),
                ('contenido', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='tienda.conversacionagente')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes del Agente',
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='mercados/')),
                ('activo', models.BooleanField(default=True)),
                ('acopiador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mercados',
            },
        ),
        migrations.CreateModel(
            name='DocumentoRAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(choices=[('producto', 'Producto'), ('productor', 'Productor'), ('receta', 'Receta'), ('faq', 'Pregunta Frecuente'), ('wiki', 'Artículo Wiki'), ('temporada', 'Temporada / Cosecha')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.producto')),
                ('productor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.productor')),
                ('mercado', models.ForeignKey(blank=True, help_text='Vacío = aplica a todos los mercados', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.mercado')),
            ],
            options={
                'verbose_name': 'Documento RAG',
                'verbose_name_plural': 'Documentos RAG',
            },
        ),
        migrations.AddField(
            model_name='conversacionagente',
            name='mercado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.mercado'),
        ),
        migrations.AddField(
            model_name='clientecorporativo',
            name='mercado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.mercado'),
        ),
        migrations.AddField(
            model_name='productor',
            name='mercado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productores', to='tienda.mercado'),
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('semanal', 'Mercado Semanal'), ('ancheta', 'Ancheta'), ('evento', 'Evento'), ('corporativo', 'Corporativo'), ('personalizado', 'Personalizado')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='paquetes/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, help_text='Null = curado por admin', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mercado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes', to='tienda.mercado')),
            ],
            options={
                'verbose_name_plural': 'Paquetes',
            },
        ),
        migrations.CreateModel(
            name='ItemPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('opcional', models.BooleanField(default=False, help_text='El cliente puede quitar este item')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tienda.paquete')),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(help_text='Ej: 200g, 1 unidad, al gusto', max_length=50)),
                ('opcional', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='tienda.producto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='tienda.receta')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
    ]
