# Generated by Django 6.0.5 on 2026-05-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_receta_producto_estado_editorial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('despensa', 'La Despensa'), ('gourmet', 'Soltero Gourmet'), ('ancheta', 'Ancheta'), ('picknick', 'De Picknick'), ('artesanias', 'Artesanías')], max_length=20),
        ),
    ]
